### PR TITLE
Use os.UserHomeDir() for Go version 1.12+

### PR DESCRIPTION
**Pull request by mgrachev**
Hi there!

Use `os.UserHomeDir()` instead of `go-homedir` for Go version 1.12+.

### CODE REVIEW

**Comment by pior** [comment]
👍

**Comment by jharshman** [comment]
@mgrachev is there an issue with using the https://github.com/mitchellh/go-homedir package?

**Comment by mgrachev** [comment]
@jharshman No, there isn't. This is a dependency and I prefer to minimize dependencies in my projects.

**Comment by jharshman** [comment]
@mgrachev Trimming back dependencies is always good, however, the `go-homedir` package itself is very small and not dependent on Go version.  I could see this comment giving the impression to a user that if s/he is using Go 1.12+ that s/he would need to edit the code to use `os.UserHomeDir()`.

**Comment by spf13** [comment]
@mgrachev I'm confused about this. How does adding this comment to the source help? Are we expecting users to change their dependency source if they are using Go 1.12+?

**Comment by mgrachev** [comment]
@spf13 Yes, you're right. I've added this comment because I didn't want to drop support for previous versions of Go.

**Comment by spf13** [comment]
I'm not sure what value there is in adding a comment. I do think there is some value in removing dependencies. One way to do this without breaking older users of Go is to incorporate build tags. 
That is, create two alternative files, with a single function in each, one using the dependency and one calling os.UserHomeDir and use build tags to manage which one is included.

**Comment by mgrachev** [comment]
@spf13 Done.

**Comment by jharshman** [comment]
I'm going to close this because it introduces complication without enough benefit.

**Comment by jpeach** [comment]
Commenting on a closed PR is pretty bad form, but `os.UserHomeDir` depends on the "$HOME" environment variable being set, whereas `go-homedir` uses a number of different strategies and basically always works whether "$HOME" is set or not.

**Comment by marckhouzam** [comment]
Looks like this has been done by #1337  and released in Cobra 1.2.

**Pull request closed without merging**
