### PR TITLE
Set up Dependabot

### PR DESCRIPTION
**Pull request by mmorel-35**

### CODE REVIEW

**Comment by umarcor** [comment]
This is a duplicate of #1427.

**Comment by mmorel-35** [comment]
Yes, but this one also handles github-actions and and is daily checked, not weekly

**Comment by umarcor** [comment]
> Yes, but this one also handles github-actions and and is daily checked, not weekly

That is correct. The netiquette in this case is to reply in #1427 in order to discuss the motivation for those differences.

**Comment by mmorel-35** [comment]
Ok, I'm closing this one then

**Pull request closed without merging**
