### PR TITLE
Add minimal Context support to cobra

### PR DESCRIPTION
**Pull request by flimzy**
RFC.  This PR is meant to demonstrate a possible, minimal solution to #563.

I welcome feedback, suggestions, and alternatives.

### CODE REVIEW

**Comment by aidansteele** [comment]
I think this would make a great addition to cobra. When I was playing with the functionality introduced in your PR, something caught me: I had assumed -- perhaps naïvely -- that a parent command's context would "trickle down" into subcommands. I tried accessing a value stored in the root command's context by accessing `child.Context()` and it wasn't there.

What semantics do you think make the most sense? I'm happy to hear that my initial assumptions were silly, but I thought it'd be worth a discussion.

**Comment by flimzy** [comment]
@aidansteele How are you trying to set context in the root command, then access in the child command? Can you show some sample code?  I'm not quite visualizing what you're doing, so it's hard to comment.

**Comment by marckhouzam** [comment]
PR #893 which has been merged has brought context support to Cobra.

This PR can therefore be closed /cc @jpmcb

**Comment by johnSchnake** [comment]
Per comment; closing.

**Pull request closed without merging**
