### PR TITLE
zsh: added custom completions

### PR DESCRIPTION
**Pull request by rsteube**
Added custom completions for zsh.

### CODE REVIEW

**Comment by zaquestion** [comment]
@spf13 @jharshman @bogem We've been using these changes over in https://github.com/zaquestion/lab for some time and they've been working as expected. Could we get some fresh eyes on this and hopefully merge. This will allow us to move off this fork and update cobra https://github.com/zaquestion/lab/issues/333#issuecomment-528622408

**Comment by rsteube** [comment]
Anyone that depends on this can use https://github.com/rsteube/cobra-zsh-gen for now.

**Comment by jharshman** [comment]
@rsteube need context on this.  What it does, and the issue it resolves.

**Comment by rsteube** [comment]
Pretty much the same as in bash: https://github.com/spf13/cobra/blob/master/bash_completions.md#creating-your-own-custom-functions

It adds the possibility for custom shell functions to be called during completion.
E.g. to provide dynamic completion arguments by calling a separate program or depend on what has already been completed previously.

Example: https://github.com/spf13/cobra/pull/884/files#diff-19e30b5d85690dcb9fe96286af3eb405R382

**Pull request closed without merging**
