### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zwhitchcox**

### CODE REVIEW

**Comment by umarcor** [comment]
@zwhitchcox, is this an unwanted PR? Or is it an unconventional way to desperately ask for help?

**Comment by zwhitchcox** [comment]
No just a joke, because I couldn't get it to work, and it was ironic, because the docs were talking about how "smart" it was.

**Comment by zwhitchcox** [comment]
Honestly though, I tried like 15 different combinations, and none of them worked

**Comment by umarcor** [comment]
> Honestly though, I tried like 15 different combinations, and none of them worked

It'd be helpful if you opened an issue telling the specific combinations you used and the errors/unexpected results you got. I understand that it can be frustrating, but unfortunately this kind of PR does neither help you nor us.

More precisely, this part of the README needs to be updated and there is an open PR about it: https://github.com/spf13/cobra/pull/904/files. Moreover, in [#910](https://github.com/spf13/cobra/issues/910#issuecomment-512794416) you'll find a practical example for a user asking about how to use cobra in a project.

**Comment by jharshman** [comment]
This kind of noise is extremely unhelpful and unwanted.  As @umarcor mentioned there are Issues and PRs that already address the documentation update which you would have seen if you took the time.

**Pull request closed without merging**
