### PR TITLE
Display sub-commands in help when runnable OR has more sub-commands

### LINKED ISSUE #43: Are commands with un-runnable parents deliberately undiscoverable?
In a program with a command structure such as `./program section command -flags`, why do un-runnable `section`s not appear in the `program`'s "Available Commands?"

You can list the child commands with `program help section`, but there's no way to find out that `section` exists. Is this intentional for some reason?

Thank you :)

### PR DESCRIPTION
**Pull request by lantins**
Fixes #43

### CODE REVIEW

**Comment by lantins** [comment]
Also note, there's also a indentation fix kindly provided by `go fmt` :)

**Comment by eparis** [comment]
Did I get this all correct via #77.  I think so.  Let me know if not!

**Comment by lantins** [comment]
I've just updated, unfortunately it doesn't fix my problem, the parent command is not directly runnable, just the child commands under it.

I guess I'll need to create a dummy `Run` function that just displays the help.

**Comment by eparis** [comment]
reopenned, i'll take another look.

**Comment by eparis** [comment]
I just created https://github.com/spf13/cobra/pull/88 to test the problem.  I must be misunderstanding, since I think this is fixed....

My test have:  runnable and unrunnable root, an unrunnable subcommand, and a runnable sub sub command.  I am running "$rootcmd help" and I see the unrunnable subcommand in the additional help topics.

What am I misunderstanding about the problem?

**Comment by lantins** [comment]
@eparis Thanks for your efforts.

I'll try again, if its not working I'll give you a way to reproduce the problem :)

**Comment by eparis** [comment]
Closing again, let me know if it isn't working!!

**Pull request closed without merging**
