### PR TITLE
enable composing PositionalArgs

### PR DESCRIPTION
**Pull request by nelz9999**
This may end up being helpful related to issues like #838 or #745...

### CODE REVIEW

**Comment by umarcor** [comment]
Hi @nelz9999! `ExactValidArgs` is deprecated in #841, since checks are orthogonalized: checking the number of arguments is decoupled from checking the values. Please see https://github.com/spf13/cobra/pull/841#issuecomment-474604947 and https://github.com/spf13/cobra/pull/841#issuecomment-474617017. Could you, please, have a look at #841 and propose this PR on top of it? I'll be pleased to include it, so that everything is merged together.

Apart from that, I would expect this PR to include additional tests to check the new feature. Some example would also be helpful to better show what you mean with 'composite positional arguments'.

**Comment by nelz9999** [comment]
Hey @umarcor... 

I took your suggestions of tests & docs, and to leave `ExactValidArgs` alone.

However, I don't think I should add on top of your #841... There's a lot of pushback and flux on that PR, which I don't think this addition needs to be a part of, since it's simply additive. I.e. this PR could get merged without any impact on #841.

**Comment by umarcor** [comment]
> I took your suggestions of tests & docs, and to leave `ExactValidArgs` alone.

Thanks!

> However, I don't think I should add on top of your #841... There's a lot of pushback and flux on that PR, which I don't think this addition needs to be a part of, since it's simply additive. I.e. this PR could get merged without any impact on #841.

Agree. Since `ExactValidArgs` is not modified now, both PRs are independent. Although they cannot be automatically merged (see https://github.com/umarcor/cobra/compare/feat-matchvalid...nelz9999:nelz%2Fargs?diff=split or https://github.com/nelz9999/cobra/compare/nelz%2Fargs...umarcor:feat-matchvalid?diff=split), I believe it will not be hard to do it.

Overall, LGTM. I would just suggest to reconsider the name of the new function/feature, tho. When I read 'composing PositionalArgs' I imagined handling positional arguments composed of more than a single word. IMHO, `MatchAll` (as proposed by @Antolius in [#745](https://github.com/spf13/cobra/issues/745#issuecomment-441326468)), `MatchMany`, `MatchMultiple`, `CheckArgs`, `ArgChecks`, `CombinedMatch`, etc. would better fit the usage: combine multiple existing checks (either built-in or custom); e.g. check ExactArgs length along with other qualities.

**Comment by nelz9999** [comment]
@umarcor I've updated the naming.

**Comment by umarcor** [comment]
> @umarcor I've updated the naming.

I saw that and I think that this PR is ready to merge; that's why I didn't add any further comment.

Unfortunately, maintainers with write permissions in this repo seem to be quite busy lately. For example #841 is ready since almost 4 months ago, but it has not been merged yet. A similar situation happened with #817.

Hence, we need to be patient and wait until @sp13, @eparis, @bogem, or any other can allocate some time. I don't know whether @jharshman has permissions or is just a regular contributor.

**Comment by umarcor** [comment]
> as an aside, looks like Travis CI is failing due to some shellcheck errors.

Indeed... https://github.com/spf13/cobra/pull/889#issuecomment-508921044

**Comment by umarcor** [comment]
@nelz9999, now that CI of the master branch is fixed, would you mind rebasing? This is so that it is not shown as 'failing', which can lead maintainers to think that this is not ready.

**Comment by nelz9999** [comment]
@umarcor Done and done!

**Comment by umarcor** [comment]
Request to be included in [1.0.0](https://github.com/spf13/cobra/milestone/2). Ref #959.

**Comment by umarcor** [comment]
Not stale, but ready to be merged.

**Comment by umarcor** [comment]
Is there anything preventing this from being merged?

**Comment by veleek** [comment]
Ping this issue!  Anything to prevent this from being merged?

**Comment by katexochen** [comment]
Will this be merged soon?

**Comment by umarcor** [comment]
@katexochen, I wouldn't bet on that. The criteria for merging PRs in this project is arbitrary and it is frequent that ready-to-merge PRs are ignored for years.

**Comment by katexochen** [comment]
@umarcor thanks for the answer, already thought so. And thanks to @nelz9999 for the work anyway.

**Comment by jpmcb** [comment]
Hi @nelz9999 - thanks so much for this, and thanks all for the patience. Any possibility you are around to rebase this and fix a merge conflict in the readme? If I don't hear from you in a week or so, I'll close this and hand it back over to the community.

**Comment by nelz9999** [comment]
@jpmcb Done!

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
