### PR TITLE
go.mod: cpuguy83/go-md2man/v2 v2.0.1

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.0...v2.0.1

- Fix handling multiple definition descriptions
- Fix inline markup causing table cells to split
- Remove escaping tilde character (prevents tildes (`~`) from disappearing).
- Do not escape dash, underscore, and ampersand (prevents ampersands (`&`) from disappearing).
- Ignore unknown HTML tags to prevent noisy warnings

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ah, looks like some tests need updating because of some of the fixes

**Comment by thaJeztah** [comment]
@eparis @estesp @cpuguy83 ptal

**Review by umarcor — APPROVED** [review]

**Review by estesp — APPROVED** [review]
LGTM

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Review by jpmcb — APPROVED** [review]
Thanks for this! LGTM

**Comment by thaJeztah** [comment]
Thanks for review/merge!

**Pull request merged**
