### PR TITLE
Custom Help verb

### PR DESCRIPTION
**Pull request by syntaqx**
Allows for the `help` verb used on the default command and flags to be changed.

### CODE REVIEW

**Comment by syntaqx** [comment]
I'm a bit confused at what test is failing here, if someone has some more knowledge about what this is that would be helpful, but I'll keep looking.

**Comment by syntaqx** [comment]
Looks like it was an issue with `fmt` on tip vs older versions. Seems that it's fixed in `master`, so it's been pulled in. Do you want me to rebase/squash the commits, or are we good to go?

**Comment by jharshman** [comment]
@syntaqx Is there a custom help verb that you prefer or one that you need to fit a use case?

**Comment by syntaqx** [comment]
I'm building a tool that's basically a joke tool, so this lets me change it to `halp`. It's a weird usecase, but non-invasive to the project so I figured it wouldn't hurt to send a PR for the changeset

**Comment by jharshman** [comment]
While it is a very small change set, I don't think it's the best fit for upstream.
@eparis your opinion?

**Comment by spf13** [comment]
I like that this is being used for a joke, but I can't think of why anyone else would need this. I'd rather keep things simpler. The only think I can think of is part of localization.

**Pull request closed without merging**
