### PR TITLE
Vgo

### PR DESCRIPTION
**Pull request by jharshman**
# Moves to resolve Issue #756 
This was a re-work of the cobra code generator to allow it to work outside of the GOPATH and hence be compatible with Go modules (vgo) introduced in Go 1.11.  This change introduces a new flag to the `init` command and deprecates the `--package` flag from the `add` command.  With all these changes the flows remains relatively the same.  Any exceptions are outlined below.

## Changes
* Add a `--pkg-name` flag to the init command which takes a string representing the package name.
e.g: `--pkg-name github.com/spf14/hugo`
* For adding commands, you should be inside your project root.
* Init will no longer fail on non-empty directories.

### CODE REVIEW

**Comment by ironsalsa** [comment]
I ran into what this fixes today. Upvote to anything that lets us use the Go Modules way of life, as some of my projects have been moved over by necessity and I'm missing the generator!

**Comment by jharshman** [comment]
@ironsalsa Yeah I think there is a lot of desire for this feature, but it's not really getting much attention from the maintainers.  There are actually a lot of open PRs on this project that aren't being attended.

**Comment by eparis** [comment]
I'm actually hoping to take a look at all of the vgo PRs today....   hopefully.   I know we need it.

**Comment by jharshman** [comment]
👍 that would be awesome @eparis thanks!!

**Comment by shawncatz** [comment]
👍

**Comment by jharshman** [comment]
@eparis were you able to review this PR?

**Comment by 1138-4EB** [comment]
ping...

**Comment by kyriediculous** [comment]
@eparis So it's been a few months now, did you manage to review it? 

This is a high priority PR...

**Comment by jharshman** [comment]
I've been using my fork of this for some time just to ensure that the usage makes sense and is stable.
So far so good.  I'm going to do a little clean up and rebase against upstream.

**Comment by williamokano** [comment]
Still nothing from the maintainers? This feature would be awesome :)

**Comment by jozuenoon** [comment]
:ping_pong:

**Comment by tsal** [comment]
@jharshman since it doesn't look like we're ever going to hear back from the maintainers on this - can you provide a write-up of how you got this working locally? I tried checking out your branch and doing a "go install ." but the binary doesn't recognize the new flag. I suspect I'm missing something dreadfully obvious.

**Comment by jharshman** [comment]
@tsal `go install` works for me.  Make sure you have the branch checked out.

**Comment by andrewmeissner** [comment]
@spf13 ping

**Comment by brainstorm** [comment]
Might totally be a PEBKAC issue, but your branch doesn't seem to install for me :/

```
$ go version
go version go1.12.4 darwin/amd64
$ cd $GOPATH/src/github.com/spf13/cobra && git checkout -b vgo
Switched to a new branch 'vgo'
$ git remote add vgo https://github.com/jharshman/cobra
$ git pull vgo vgo
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 172 (delta 78), reused 107 (delta 78), pack-reused 64
Receiving objects: 100% (172/172), 24.43 KiB | 962.00 KiB/s, done.
Resolving deltas: 100% (104/104), completed with 12 local objects.
From https://github.com/jharshman/cobra
 * branch            vgo        -> FETCH_HEAD
 * [new branch]      vgo        -> vgo/vgo
Updating 67fc483..35a3584
Fast-forward
 .gitignore                        |   2 +
 cobra/cmd/add.go                  | 122 ++++++++++++++-------------------------------
 cobra/cmd/add_test.go             |  92 ++++++++++------------------------
 cobra/cmd/init.go                 | 229 ++++++++++++++-----------------------------------------------------------------------
 cobra/cmd/init_test.go            |  87 +++++++++-----------------------
 cobra/cmd/project.go              | 222 ++++++++++++++++++++++------------------------------------------------------------
 cobra/cmd/project_test.go         |  23 +--------
 cobra/cmd/root.go                 |   3 +-
 cobra/cmd/testdata/main.go.golden |  29 +++++------
 cobra/cmd/testdata/root.go.golden | 124 ++++++++++++++++++++++++----------------------
 cobra/cmd/testdata/test.go.golden |  27 +++++-----
 cobra/tpl/main.go                 | 153 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 12 files changed, 433 insertions(+), 680 deletions(-)
 create mode 100644 cobra/tpl/main.go

$ go install github.com/spf13/cobra/cobra
# github.com/spf13/cobra
./command.go:31:25: undefined: pflag.ParseErrorsWhitelist
$ cobra init --pkg-name github.com/foo/bar
Error: unknown flag: --pkg-name
(...)
```

**Comment by gmelillo** [comment]
Some news about that?
will be really useful to have it merged

**Comment by umarcor** [comment]
> @jharshman since it doesn't look like we're ever going to hear back from the maintainers on this - can you provide a write-up of how you got this working locally? I tried checking out your branch and doing a "go install ." but the binary doesn't recognize the new flag. I suspect I'm missing something dreadfully obvious.

I hope that the following example is useful to you:

``` bash
#!/bin/sh

cat > run.sh <<-EOF
apk add git
git clone -b vgo https://github.com/jharshman/cobra cobra
cd cobra/cobra
go install
cobra
EOF

$(command -v winpty) docker run --rm -it golang:alpine sh -c "$(cat run.sh)"
```

**Pull request merged**
