### PR TITLE
Add OnInitializeE

### PR DESCRIPTION
**Pull request by fmenezes**
Today we have `cobra.OnInitialize` but unfortunately we don't have an API to return initialization errors.

This aims to add `cobra.OnInitializeE` to accept `func() error` and returns error accordingly.

### CODE REVIEW

**Comment by marckhouzam** [comment]
Hi @fmenezes.  Could you provide a description of what this PR does and if it aims to fix an existing issue.
Thank you.

**Comment by fmenezes** [comment]
> Hi @fmenezes.  Could you provide a description of what this PR does and if it aims to fix an existing issue.
> 
> Thank you.

Hi @marckhouzam, my mistake, I completely forgot to add it. It is there now.

Let me know if you want more clarifications.

Thanks for the quick reply.

**Comment by johnSchnake** [comment]
Is there an issue for this?

Also, I noticed in the implementation that you call the `preRunE` then `preRun`; this  is a bit different than the other `xyzE` methods since it is assumed you choose either one or the other, not both. Was there a reason for this particular implementation? It may be the right one, I just wanted context on the choice.

**Comment by fmenezes** [comment]
> Is there an issue for this?
> 
> Also, I noticed in the implementation that you call the `preRunE` then `preRun`; this is a bit different than the other `xyzE` methods since it is assumed you choose either one or the other, not both. Was there a reason for this particular implementation? It may be the right one, I just wanted context on the choice.

@johnSchnake thanks for pointing out, I have no strong preference I can keep it consistent with the same behavior and check if `preRunE` has been set otherwise go with `preRun`.

**Comment by fmenezes** [comment]
I _think_ this PR addresses #798

**Review by jpmcb — CHANGES_REQUESTED** [review]
I need to more fully understand why we need this.

I also haven't used the initializers much before so I'm unsure what this is solving or what user workflow this would work well for that other APIs can't fulfill.

I'm all for propagating errors, but I don't want to flood the API just for the sake of have 1 to 1 `abc` and `abcE` methods.

---

Anyone in the community have a user story or issue that this would solve for you?

**Comment by fmenezes** [comment]
@jpmcb my example lies on https://github.com/mongodb/mongodb-atlas-cli/blob/1c845fa25ad07e5c62266a91de8d14c348caca37/cmd/mongocli/mongocli.go#L100 for mongodb-atlas-cli we have to handle early exits ourselves and now that we are adding tracking capabilities we have to figure out which command was "early exited".

**Comment by fmenezes** [comment]
tagging @jpmcb for copy review

**Pull request closed without merging**
