### PR TITLE
completions: fix mixed tab/spaces indentation

### PR DESCRIPTION
**Pull request by thaJeztah**
These templates use 4 spaces for indentation, but some lines used tabs.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@jpmcb  @Luap99 ptal

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by Luap99** [comment]
@marckhouzam PTAL
I think we should setup some linter for the generated files.

**Comment by thaJeztah** [comment]
> I think we should setup some linter for the generated files.

Once support for Go 1.15 is dropped, these templates could potentially stored as separate files (go template?), and included using `//go:embed`, which would (potentially) make validation/linting easier.

**Review by marckhouzam — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]
I wonder if this is going to cause problems with go editors that default to using tabs. Was there an actual problem with these, or is this just cosmetic?

Regardless, I think it's fine to change it - I prefer consistency and makes sense for shell code.

**Comment by thaJeztah** [comment]
> I wonder if this is going to cause problems with go editors that default to using tabs.

I don't think editors should format content inside string-literals, but even in that case, this patch shouldn't change that (as there's already content using the same indentation)

> Was there an actual problem with these, or is this just cosmetic?

No real problem as far as I'm aware, but it looked sloppy to have a generated file that doesn't stick to its own coding style 😅

**Review by jpmcb — APPROVED** [review]
Looks good - but let's keep a close eye on this in case people report issues with tabs vs. spaces in their generated

**Pull request merged**
