### PR TITLE
🍁 Fall 2021 - release candidate

### PR DESCRIPTION
**Pull request by umarcor**
I rebased the PRs listed in #1496 into a branch.

/cc @marckhouzam @jpmcb

### CODE REVIEW

**Comment by marckhouzam** [comment]
This is very useful. I am worried of not having enough soak time for all these PRs interacting together, so this branch will allow running different test suites to help make sure we have a stable release.

Thanks @umarcor

**Comment by jpmcb** [comment]
Amazing!!! Love this idea - we should totally have a release candidate PR for each release. Thanks much for this - will also use for some testing

**Comment by umarcor** [comment]
@jpmcb regardless of the merging order in this PR, go ahead and pick the changes at your own will. I'll keep rebasing and reorganising this PR if necessary.

**Comment by jpmcb** [comment]
Sweet! Slow going on my end, apologies, but we will make it through this release hopefully soon! 💪🏼

**Comment by marckhouzam** [comment]
I've run the completion automated tests (https://github.com/marckhouzam/cobra-completion-testing) on this release candidate as well as helm's go tests and helm's acceptance completion tests (https://github.com/helm/acceptance-testing) and everything passes.  It is not guarantee but it is a good sign.

However, I've expressed concerns directly in #1495 (which has now been removed from the release candidate) and #1500.

**Comment by umarcor** [comment]
Closed because this PR served its purpose already. See #1496.

**Comment by marckhouzam** [comment]
This was a really useful initative. Thanks for doing it @umarcor !

**Comment by jpmcb** [comment]
Agreed - I really want to make this apart of all future release cycles. Was really helpful for trying out builds as we merged things.

**Pull request closed without merging**
