### PR TITLE
add arduino-cli to projects using cobra

### PR DESCRIPTION
**Pull request by umbynos**
arduino-cli has been using cobra for [almost a year](https://github.com/arduino/arduino-cli/commit/6a2d8de4f3ff7011f29637eac658b07fcbf8f5b3#diff-37aff102a57d3d7b797f152915a6dc16).
I'm also working in [adding shell completion](https://github.com/arduino/arduino-cli/pull/663) using the latest features of cobra 1.0.0

### CODE REVIEW

**Comment by marckhouzam** [comment]
> I'm also working in [adding shell completion](https://github.com/arduino/arduino-cli/pull/663) using the latest features of cobra 1.0.0

Cool.  I notice you had to replace the `-` by a `_` for fish after generating completions. @umbynos would you mind opening an issue for Cobra to explain the problem?.  I think we should fix this directly in Cobra.  You are also welcomed to provide a PR if you wish.

**Comment by marckhouzam** [comment]
This is an easy merge @jpmcb

**Review by jpmcb — APPROVED** [review]
Thanks for this! And thanks mark for the heads up!! 🚀

**Comment by silvanocerza** [comment]
Thank you very much! Really appreciated. :smile:

**Pull request merged**
