### PR TITLE
Adding ability to add nested commands through `cobra add`

### PR DESCRIPTION
**Pull request by ianwalter**
- Modified `cobra add` command to be able to parse argument into nested command structure (#266)
- Modified `createCmdFile` function to accept cmdPath
- Modified cmdFile template to specify package name, import it's child package if necessary, and to TitleCase command names so that they can be accessed by parent packages
- Added getChildNames helper function so that child commands can be added to their parent
- Simplified `writeTemplateToFile` function syntax.

### CODE REVIEW

**Comment by ianwalter** [comment]
Not sure why this is failing with go 1.3.3 all of a sudden but it also failed in #271 so I don't think it is specific to my changes!

**Comment by mattstratton** [comment]
Any idea when this will be merged? I think it's exactly what I need for a project right now...

**Comment by jmdots** [comment]
I need this too :).   Looks dormant.

**Comment by mattstratton** [comment]
Any thoughts on when this might be merged?

**Comment by bogem** [comment]
@eparis

**Comment by eparis** [comment]
I'll leave it for @spf13   I've never even looked at the code under `cmd/`

**Pull request closed without merging**
