### PR TITLE
update viper to v1.4.0

### LINKED ISSUE #938: ambiguous import: found github.com/ugorji/go/codec in multiple modules when i use cobra and gin both
I noticed viper v1.4.0 use the package "github.com/ugorji/go v1.1.4 // indirect", but cobra v0.0.5 still used viper v1.3.2

So can you upgrade cobra go.mod with viper 1.4.0

### LINKED ISSUE #978: Bump viper version from 1.3.2 to 1.4.0
This resolves the vulnerability detected in gojisvm/gojis#72 and only leaves gojisvm/gojis#75, which can be fixed in a future release of spf13/viper.

### PR DESCRIPTION
**Pull request by umarcor**
Fix #938
Fix #978

### CODE REVIEW

**Comment by umarcor** [comment]
@KowloonZh, @plo-, do you mind testing/reviewing this?

**Comment by plo-** [comment]
Seems ok for me, thanks!

**Comment by KowloonZh** [comment]
> Seems ok for me, thanks!

hi, plo

could you please tell my how to testing it.

i failed by use go get github.com/spf13/cobra@a4bc1a0fefe97a46dddf831c9648b18336be751e, either failed by use  go get github.com/umarcor/cobra@update-viper.

anyway, i think it will works for me when the viper version is up to 1.4

**Comment by umarcor** [comment]
@KowloonZh you might try temporaly adding `replace github.com/spf13/cobra => github.com/umarcor/cobra update-viper` to the `go.mod` file of your project.

**Comment by KowloonZh** [comment]
> @KowloonZh you might try temporaly adding `replace github.com/spf13/cobra => github.com/umarcor/cobra update-viper` to the `go.mod` file of your project.

thank you very much for help,

i had add `replace github.com/spf13/cobra => github.com/umarcor/cobra v0.0.6-0.20190917162959-a4bc1a0fefe9` to the `go.mod` file, but it not works to me, anything else i missed? my repo link is `https://github.com/hulklab/yago`

**Comment by umarcor** [comment]
```sh
docker run --rm -it golang bash -c "
git clone https://github.com/hulklab/yago
cd yago
go build
"
```

works here. what are you trying to fix?

**Comment by KowloonZh** [comment]
hi, umarcor
thank you at first.

it works fine cause i add the replace statement `replace github.com/ugorji/go v1.1.4 => github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43` at the end of go.mod in master branch

i pushed the my branch `viper_update` and please run the following command, then you can see the problem:
```
docker run --rm -it golang bash -c "
git clone https://github.com/hulklab/yago
cd yago
git checkout viper_update
go build
"
```
the error output just like this:

```
ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181022190402-e5e69e061d4f (/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181022190402-e5e69e061d4f)
```

**Comment by umarcor** [comment]
@KowloonZh, I think that you do need the replace statement indepently of viper being updated to `v1.4.0`. This is because ugorji/go needs to be updated to `v1.1.7`: https://github.com/ugorji/go/releases/tag/v1.1.7. Apart from vipe `v1.4.0`, there is another dependency in your `go.mod` (https://github.com/hulklab/yago/blob/master/go.mod#L14) that is using `v1.1.4` of ugorji/go: https://github.com/gin-gonic/gin/blob/v1.4.0/go.mod#L13. Hence, new fixed releases of gin-gonic/gin, spf13/viper and spf13/cobra need to be published before you can remove the replace statement.

**Pull request merged**
