### PR TITLE
maintainers: update

### PR DESCRIPTION
**Pull request by umarcor**

### CODE REVIEW

**Comment by umarcor** [comment]
CI is failing because of #1926.

**Comment by marckhouzam** [comment]
Let's not remove spf13. Ever 😁
And when was @johnSchnake 's last interaction with the project?

**Comment by umarcor** [comment]
> Let's not remove spf13. Ever grin

The proposal is to move them to the 'inactive' section, not to remove anyone.

> And when was @johnSchnake 's last interaction with the project?

According to what's "easily" searchable, April-May 2022:

- https://github.com/spf13/cobra/commits?author=johnSchnake
- https://github.com/spf13/cobra/issues?q=sort%3Aupdated-desc+author%3AjohnSchnake+
- https://github.com/spf13/cobra/issues?q=sort%3Aupdated-desc+commenter%3AjohnSchnake+

**Comment by marckhouzam** [comment]
Poor phrasing on my part. "Let's not mark spf13 as inactive."

**Pull request closed without merging**
