### PR TITLE
Rewrite tests

### LINKED ISSUE #541: Refactor tests
The current tests are difficult to read, understand and debug because of a lot of global commands and flags:
```go
var tp, te, tt, tr []string
var rootPersPre, echoPre, echoPersPre, timesPersPre []string
var flagb1, flagb2, flagb3, flagbr, flagbp bool
var flags1, flags2a, flags2b, flags3, outs string
var flagi1, flagi2, flagi3, flagi4, flagir int
var rootcalled bool
var versionUsed int


var cmdHidden = &Command{
	Use:   "hide [secret string to print]",
	Short: "Print anything to screen (if command is known)",
	Long:  `an absolutely utterly useless command for testing.`,
	Run: func(cmd *Command, args []string) {
		outs = "hidden"
	},
	Hidden: true,
} ...
```

My proposal is to rewrite these tests, comment and make them most independently from global state. 

Good examples:
```go
// TestUseDeprecatedFlags checks,
// if cobra.Execute() prints a message, if a deprecated flag is used.
// Related to https://github.com/spf13/cobra/issues/463.
func TestUseDeprecatedFlags(t *testing.T) {
	c := &Command{Use: "c", Run: func(*Command, []string) {}}
	output := new(bytes.Buffer)
	c.SetOutput(output)
	c.Flags().BoolP("deprecated", "d", false, "deprecated flag")
	c.Flags().MarkDeprecated("deprecated", "This flag is deprecated")

	c.SetArgs([]string{"c", "-d"})
	if err := c.Execute(); err != nil {
		t.Error("Unexpected error:", err)
	}
	if !strings.Contains(output.String(), "This flag is deprecated") {
		t.Errorf("Expected to contain deprecated message, but got %q", output.String())
	}
}
```

```go
// TestHelpFlagInHelp checks,
// if '--help' flag is shown in help for child (executing `parent help child`),
// that has no other flags.
// Related to https://github.com/spf13/cobra/issues/302.
func TestHelpFlagInHelp(t *testing.T) {
	output := new(bytes.Buffer)
	parent := &Command{Use: "parent", Run: func(*Command, []string) {}}
	parent.SetOutput(output)

	child := &Command{Use: "child", Run: func(*Command, []string) {}}
	parent.AddCommand(child)

	parent.SetArgs([]string{"help", "child"})
	err := parent.Execute()
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(output.String(), "[flags]") {
		t.Errorf("\nExpecting to contain: %v\nGot: %v", "[flags]", output.String())
	}
}
```

### PR DESCRIPTION
**Pull request by bogem**
* Add tests for args.go
* Get rid of global commands and flags
* Move the tests, related to command.go, to command_test.go
* More comments
* More tests

Fixes #541

### CODE REVIEW

**Comment by bogem** [comment]
At the moment coverage improved from 85% to 86.6%.

**Comment by bogem** [comment]
The coverage of `go test` decreased to 84.5% because of not using of ResetCommands and ResetFlags.

**Comment by bogem** [comment]
Delete WIP status. I did all I want in this PR.
@eparis, @spf13, @anthonyfok, @dnephin, what do you think about it? Maybe you have more proposals about tests?

**Comment by dnephin** [comment]
All these changes sound great to me. The new tests looks good too.

**Comment by bpicode** [comment]
As a general idea: is there something where [testable examples](https://blog.golang.org/examples) are reasonable? godoc would certainly profit.

**Comment by bogem** [comment]
@bpicode Completely forgot about it. I will open a separate issue for it. Thank you!

**Pull request merged**
