### PR TITLE
Added an UnknownCommandFunc to allow for custom handling of unknown commands

### PR DESCRIPTION
**Pull request by markbates**

### CODE REVIEW

**Comment by markbates** [comment]
@spf13 ping

**Comment by vjeantet** [comment]
I like this feature, can we see it merged ?

**Comment by spf13** [comment]
@markbates This is a great idea. Sorry for sitting on it so long. I'm just catching up now on many of my projects and haven't reviewed this thoroughly. I would expect that the unknownCommandFunction would cascade up the tree to the root. Meaning I can write custom handling for my entire application on the root or I can define specific handling for subcommands. It doesn't appear that this code does this. What do you think?

**Comment by markbates** [comment]
Yeah, if I remember this correctly, it just handles the use case of the calling an unknown command on another command. It doesn't walk up the tree. It would be great if it did.

**Comment by spf13** [comment]
Do you want to extend it to do that? If you do (and document it), I'll gladly merge it.

**Comment by bogem** [comment]
I also support this idea, but please don't forget to make tests for it!

**Comment by vjeantet** [comment]
Hello,

This is my workaround to handle unknow command.

     root.go (RootCmd)  

```go
func Execute() {
	// Workaround to "forward" to a know command when no know command found
	_, _, err := RootCmd.Find(os.Args[1:])
	if err != nil && strings.HasPrefix(err.Error(), "unknown command") {
		// insert my command "run" in args
		os.Args = append(os.Args[:1], append([]string{"run"}, os.Args[1:]...)...)
	}

	if err := RootCmd.Execute(); err != nil {
		fmt.Println("cmd execute error: ", err)
		os.Exit(-1)
	}
}
```

**Comment by eparis** [comment]
I think this was a great idea, but it's been over a year. I'm going to close this PR, but if you ever do want to continue the project would be very interested in something which addresses both https://github.com/spf13/cobra/pull/369#issuecomment-296311314 and https://github.com/spf13/cobra/pull/369#issuecomment-343626299

**Pull request closed without merging**
