### PR TITLE
update go-yaml to v3

### PR DESCRIPTION
**Pull request by umarcor**

### CODE REVIEW

**Comment by jharshman** [comment]
@umarcor is there a reason for the update?
PR descriptions should never be blank.

**Comment by umarcor** [comment]
@jharshman, there is no special reason, but the preference to slowly keep up to date, instead of having large conflicts afterwards. That's why there is no description. Unlike #953, this is just a *chore*.

BTW, spf13/pflag v1.0.5 was released two weeks ago. I didn't open a PR yet, because of the *maintenance status*.

**Comment by jharshman** [comment]
> That's why there is no description. Unlike #953, this is just a chore.

PR descriptions should never be blank, even for a "chore".  This causes maintainers to guess _why_ this PR has been opened.  i.e: bug fixes? new feature?

**Comment by jharshman** [comment]
Looks like they have not tagged a v3.0.0 release yet.
Gonna hold off on upgrading for the time being.
https://github.com/go-yaml/yaml/issues/487

**Comment by umarcor** [comment]
Sure. There is also v2.2.3. I could update the PR accordingly.

Nevertheless, I think that #953 is prioritary. By the time we have other prioritary PRs merged, there might be a tagged v3.0.0 for go-yaml.

**Pull request closed without merging**
