### PR TITLE
Remove some wonky error handling, as upstream seems correct now.

### PR DESCRIPTION
**Pull request by brendandburns**
Also, it's buggy for nested commands.

### CODE REVIEW

**Comment by brendandburns** [comment]
This is dependent on https://github.com/spf13/pflag/pull/7 for tests to pass.

**Comment by spf13** [comment]
LGTM

**Comment by spf13** [comment]
This is actually not passing for me even after merging spf13/pflag#7 . @brendandburns can you take another look at it.

**Comment by spf13** [comment]
Actually it looks like spf13/pflag#7 broke these tests. Still, @brendandburns can you look at it?

**Comment by brendandburns** [comment]
Sorry! Will look into it..

**Comment by brendandburns** [comment]
ok, I fixed this up to properly handle help messages.  tests are now passing.

Thanks!
--brendan

**Comment by spf13** [comment]
Thanks @brendandburns

**Comment by spf13** [comment]
Merged as 9e7273d

**Pull request closed without merging**
