### PR TITLE
Add ORY Hydra & Kratos to projects_using_cobra.md

### PR DESCRIPTION
**Pull request by vinckr**

### CODE REVIEW

**Review by marckhouzam — CHANGES_REQUESTED** [review]
@vinckr thanks for the contribution.  Could you place the two new projects in alphabetical order?

**Comment by vinckr** [comment]
> @vinckr thanks for the contribution. Could you place the two new projects in alphabetical order?

I put them both under 'O' now.

**Comment by tacurran** [comment]
Ory Hydra (github.com/ory/hydra)
Ory Kratos (github.com/ory/hydra)

**Comment by marckhouzam** [comment]
> Ory Hydra (github.com/ory/hydra)
> Ory Kratos (github.com/ory/kratos)

@tacurran Do you mean that it should be `Ory` and not `ORY`?

**Review by marckhouzam — APPROVED** [review]
@jpmcb  an easy one

**Review by jpmcb — APPROVED** [review]
Looks great!! And thanks marc - you the real MVP 🚀

**Pull request merged**
