### PR TITLE
Add VMware Tanzu Framework to projects

### PR DESCRIPTION
**Pull request by mamachanko**

### CODE REVIEW

**Review by umarcor — CHANGES_REQUESTED** [review]
Since VMware Tanzu is listed already, better change the existing URL so that it points to the org and not to a single repo.

**Comment by mamachanko** [comment]
> Since VMware Tanzu is listed already (#1501), better change the existing URL so that it points to the org and not to a single repo.

@umarcor changed to PR to mention both projects on one line.

**Comment by umarcor** [comment]
@mamachanko thanks! I added this PR to #1454, #1496 and #1525.

**Review by umarcor — APPROVED** [review]

**Comment by jpmcb** [comment]
Thanks for this! Commit was included in bigger PR here: #1454

**Pull request closed without merging**
