### PR TITLE
doc: add ReST doc generation

### PR DESCRIPTION
**Pull request by shahidhk**
Added `GenReST` commands to generate docs in [ReStructured Text](http://docutils.sourceforge.net/rst.html) format.

This is exactly similar to `GenMan` and `GenMd` commands. To deal with document processors like [Sphinx](http://www.sphinx-doc.org/en/stable/), which can cross link documents using `:ref:` tags, `linkHandler` function can be used.

### CODE REVIEW

**Comment by bogem** [comment]
LGTM
/cc @eparis

**Comment by shahidhk** [comment]
@bogem @eparis Any update on this? Thanks

**Comment by bogem** [comment]
Please add a reference to docs in README as it shown [here](https://github.com/spf13/cobra#generating-markdown-formatted-docs).

**Comment by shahidhk** [comment]
@bogem Done. I have also combined all three document generation headings into one. Hope that's fine.

**Comment by bogem** [comment]
Please resolve conflicts and add link to Table of Contents.

**Comment by shahidhk** [comment]
@bogem sorry about that. I have merged master and fixed conflicts, also added to ToC

**Comment by shahidhk** [comment]
Looks like some tests are failing on circleci:
```
--- FAIL: TestNormConsistent (0.00s)
	cobra_test.go:1253: Normalizing flag names should not result in duplicate flags
```
happened on my local too. But passed on travis.

**Comment by bogem** [comment]
> happened on my local too

Update pflag on your machine: `go get -u github.com/spf13/pflag`

**Comment by bogem** [comment]
Thank you for your PR!

**Comment by shahidhk** [comment]
Thanks @bogem for guiding me through this.

**Pull request merged**
