### PR TITLE
test if flag is a bool before setting inFlag

### PR DESCRIPTION
**Pull request by wxio**
Bug fix to get the following to work 
```
cli --boolflag command
```
Currently `command` is attached to the boolean flag.
According to pflag 
https://github.com/spf13/pflag#command-line-flag-syntax
```
// boolean or flags where the 'no option default value' is set
-f
-f=true
-abc
but
-b true is INVALID
```

Therefore boolean flags not set inFlag.

There seems to be inconsistencies is c.Flags() earlier on, hence adding the call to merge.
Also I don't understand why `NoOptDefVal` is not set for booleans as is appeared to be automatic by pflag.

### CODE REVIEW

**Comment by dnephin** [comment]
Could you write a test that shows the bug?

**Comment by eparis** [comment]
If think you are saying that you have: `flag.Value.Type() == "bool"` but that `flag.NoOptDefVal == ""`  I believe that shouldn't happen...  Can you write a test how that happened.

**Comment by wxio** [comment]
@dnephin @eparis  take a look at 
https://github.com/wxio/cobra/tree/pr615test/tests

The issue may involve the combination of
```
var rootCmd = &cobra.Command{
	TraverseChildren: true,
}
```
and
```
var subCmd = &cobra.Command{
	Use:                "sub",
	DisableFlagParsing: true,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Printf("sub called with args %v", args)
	},
}
```

**Comment by wxio** [comment]
see https://github.com/spf13/cobra/pull/616

**Pull request closed without merging**
