### PR TITLE
https://github.com/umarcor/cobra/pull/20

### PR DESCRIPTION
**Pull request by macoMarv86**
dependabot/go_modules/github.com/cpuguy83/go-md2man/v2-2.0.1
dependabot-preview-bot-added-dependencies
https://github.com/cpuguy83/go-md2man
forked-from-spf13/cobra/umarcor/cobra

### CODE REVIEW

**Review by macoMarv86 — COMMENTED** [review]
https://github.com/umarcor/cobra/pull/20 #1498
macoMarv86:master
.Github/dependabot.yml
BumpGithub.com/spf13/viper from 1.7.0 to 1.8.1

**Review by macoMarv86 — COMMENTED** [review]
Create Github dependabot.yml
github-dependabot/-#1427/-configuration file
 Co-Authored-By: Matthieu MOREL <mmorel-35@users.noreply.github.com>
 Co-Authored-by: macoMarv86<marvinneira44@gmail.com

**Review by macoMarv86 — COMMENTED** [review]
Create Github dependabot.yml
github-dependabot/-#1427/-configuration file
 Co-Authored-By: Matthieu MOREL <mmorel-35@users.noreply.github.com>
.Github/dependabot.yml
 Co-Authored-By: macoMarv86<marvinneira44@gmail.com

**Comment by umarcor** [comment]
I guess this PR is the unwanted result of tinkering with some CLI tool or some git/github extension for some IDE?

**Review by jpmcb — CHANGES_REQUESTED** [review]
Looks to be an accidental PR. Please re-open with a valid description that references an issue if this was wanted

**Pull request closed without merging**
