### PR TITLE
Fix escaping of % in bash code strings

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
Ptal @eparis

**Comment by eparis** [comment]
Seems more like: https://github.com/spf13/cobra/pull/256/files#diff-3db5cab63dbb32fff4264f5449fd2904L25 should be a `Fprint`, instead of `Fprintf`

**Comment by sttts** [comment]
Either is fine. In fact, there is another line with `%%` which is slightly broken due to printf interpretation.

**Comment by eparis** [comment]
I'd rather see less crazy escapism since it makes it easier for the next person to stumble along.

**Pull request merged**
