### PR TITLE
powershell completion fix no file comp directive

### LINKED ISSUE #1362: PowerShell completion does not always honour ShellCompDirectiveNoFileComp
This is the same as part of #1248 (fish), as well as #1212 (zsh).

The `powershell` completion script disables file completion only if it receives no completions from the `__complete` command.  Notice the last line of:
https://github.com/spf13/cobra/blob/eb3b6397b1b5d1b0a2cd66a9afe0520f480c0a87/powershell_completions.go#L143-L146

However, it is valid for `ValidArgsFunction` to return completions that don't apply to the current `toComplete` prefix. This means file completion should still be disabled if requested by the directive, but the script does not realize it as it still believes it received valid completions.

Say I have the following `ValidArgsFunction` for command `nofilecomp`:
```
ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
    // We do not consider the toComplete prefix and always return a completion
    return []string{"why"}, cobra.ShellCompDirectiveNoFileComp
},
```
If I have a file called `myfile` and run in powershell:
```
$ ./testprog nofilecomp my<TAB>
```
I would expect not to get file completion, but I do, and `myfile` gets completed. This is because
```
$ ./testprog __complete nofilecomp my<ENTER>
why
:0
Completion ended with directive: ShellCompDirectiveNoFileComp
```
Notice that above, the script receives a completion even though it is not technically valid. This is allowed. But then, the script does not realize it must disable file completion.

/cc @Luap99

### PR DESCRIPTION
**Pull request by Luap99**
Make sure to filter the returned completions before we check if there are valid completions left.

Fixes #1362

### CODE REVIEW

**Comment by Luap99** [comment]
@umarcor The MINGW64 workflow is failing with a missing go module. Can you take a look?

/cc @jpmcb

**Review by marckhouzam — APPROVED** [review]
Thanks for the quick fix @Luap99, works great.

**Comment by umarcor** [comment]
@Luap99, see #1366.

**Review by jpmcb — APPROVED** [review]
LGTM - thanks for the patience on this one!

**Pull request merged**
