### PR TITLE
Replace *bytes.Buffer with io.Writer

### PR DESCRIPTION
**Pull request by mvdan**
Also adds support for generating bash completions on writers other than
just buffers.

Found via github.com/mvdan/interfacer.

### CODE REVIEW

**Comment by mvdan** [comment]
I just realised that all the buffer functions were ignoring errors since buffers will never error on writes. I need to fix this.

**Comment by mvdan** [comment]
Done. The patch is larger now, and the writing code is a bit uglier, but I don't think of a better way to treat write errors.

**Comment by eparis** [comment]
looks like the patch needs to be rebased...

**Comment by eparis** [comment]
should we do something similar in the markdown docs generation?

**Comment by mvdan** [comment]
@eparis yeah, but the rebase should be trivial. Will do.

Regarding markdown doc generation, I didn't notice since it wasn't using `*bytes.Buffer`. Limiting to a buffer and not checking errors is fine, as is using a writer and checking errors. But mixing the two really doesn't work.

I can also fix that code if you confirm that adding error checking verbosity everywhere is fine. If you have suggestions on how to avoid `err != nil` on every write, I'm all ears. Otherwise, I'll update this PR.

**Comment by eparis** [comment]
That's just golang, we're going to have to do the `if err != nil`...   You can save a line using 
```
if _, err := fmt.Fprintf(w, "__start_%s()\n", name); err != nil {
```
But basically, I think you did the best you can....

**Comment by mvdan** [comment]
Indeed, I can save a line. But if you look at the diff, I avoided doing that in cases where the write is multi-line. Mainly to avoid awkwardness such as:

```go
if _, err := fmt.Fprintf(w, `some
multiline
string`); err != nil {
    // ...
}
```

So should I include the markdown generation error stuff in this PR as well, or should I do that in a separate PR to keep this one smaller and easier to merge?

**Comment by eparis** [comment]
You tell me what makes you happy. I'll go with that   :)

**Comment by mvdan** [comment]
Cool! I've just rebased this PR and will do the other in a separate one then. This one is big enough as it is.

**Pull request merged**
