### PR TITLE
deprecate ExactValidArgs in favour of MatchAll(OnlyValidArgs, ...)

### PR DESCRIPTION
**Pull request by umarcor**
This is a subset of #1643, which is a subset of #841.

### CODE REVIEW

**Comment by marckhouzam** [comment]
This is so close to #1643, I'm not sure we can't go straight to merging #1643.

Let's see which approach @jpmcb prefers.

**Comment by jpmcb** [comment]
Any reason for splitting this up into multiple PRs?

_Generally,_ I think i'd prefer to tackle in as few PRs as possible. But if it makes sense to do multiple, that's fine. 

I don't have a ton of context on this, so let me familiarize myself and get back on this

**Comment by umarcor** [comment]
> Any reason for splitting this up into multiple PRs?

Having it all together did delay the contribution several years, because it was apparently too much to tackle. Splitting into smaller pieces is allowing to slowly get the content merged.

On the other hand, according to https://github.com/spf13/cobra/commit/ab42c937ec7c62b0345f61c3e950cb785a470dc7, #1643 might produce an error because it modifies more than 200 lines.

> I don't have a ton of context on this, so let me familiarize myself and get back on this

See https://github.com/spf13/cobra/pull/1643#issuecomment-1080023276.

**Comment by umarcor** [comment]
@jpmcb can we please merge this M-sized PR to move forward with the series?

**Comment by marckhouzam** [comment]
I vote for merging #1643 directly

**Comment by umarcor** [comment]
#1643 is a superset, so merging any of them will solve this.

**Comment by umarcor** [comment]
*ping* @spf13 @johnSchnake @jpmcb @marckhouzam

**Comment by marckhouzam** [comment]
I'm reviewing and expect to merge #1643 which is a superset of this one.  So I believe we can close this one.
Please reopen @umarcor if I misunderstood.

**Pull request closed without merging**
