### PR TITLE
fix: fish output redirection

### LINKED ISSUE #1246: Fish completion error
```sh
Expected a command, but instead found a redirection
complete --do-complete "faas " &> /dev/null
```
I think it should be:
```sh
complete --do-complete "faas " 2> /dev/null
```

### PR DESCRIPTION
**Pull request by matejvasek**
resolves #1246

### CODE REVIEW

**Comment by marckhouzam** [comment]
Thanks @matejvasek, to make sure we don't break this again, could you put a comment not to use `&>` because Fish 3.0 does not support it?

**Comment by matejvasek** [comment]
@marckhouzam comment added.

**Review by marckhouzam — APPROVED** [review]
Thanks.
I've tested this with Fish 3.1 and things continue to work as expected.

@jharshman this looks safe.

**Review by jharshman — APPROVED** [review]
thank you @matejvasek for your PR and @marckhouzam for your review!

**Pull request merged**
