### PR TITLE
Bash completion aliases

### PR DESCRIPTION
**Pull request by rajatjindal**
This is continuation of PR #588 ( i messed up branch during rebasing from master).

I've taken out the code to support "cobra command aliases" which needed to use flaghash. I will work on that as a separate PR.

This current changes are just to support bash aliases for the root command

so we can do like: 

alias aliasname=origname
complete -o default -F __start_origname aliasname

and then we can use aliasname with completions working.

### CODE REVIEW

**Comment by rajatjindal** [comment]
@eparis sorry for taking so long. I have broken original PR into two different PR:

1. Support bash aliases for the cobra commands (this PR)
2. Support cobra aliases in completions (will open this later as it needs more work for flaghash changes).

Can you please merge this PR if the changes looks ok.

**Comment by rajatjindal** [comment]
Ping @eparis

**Comment by eparis** [comment]
What exactly is this supposed to be giving me that I didn't have before?

**Comment by rajatjindal** [comment]
if you create a command alias without this fix and try to use completion, it does not work.

alias aliasname=origname
complete -o default -F __start_origname aliasname

aliasname <tab><tab> will result in:

aliasname origname

and then

aliasname origname <tab><tab> will give you completion results.


after the fix:

aliasname <tab><tab> will give you correct completion results

this was reported here too: https://github.com/kubernetes/kubectl/issues/120

**Comment by eparis** [comment]
Perfect, want to get that example somehow in the godoc and I'll merge?

**Comment by rajatjindal** [comment]
sure thing. added the documentation for bash aliases

**Comment by rajatjindal** [comment]
thank you for merging the PR

**Pull request merged**
