### PR TITLE
Update Viper to 1.8.0

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes #1406
Fixes #1404
Fixes #1364

### CODE REVIEW

**Comment by li0nel** [comment]
+1 and thanks for opening this PR. Any idea when it will be merged?

**Comment by li0nel** [comment]
Any update?

**Review by umarcor — APPROVED** [review]

**Comment by li0nel** [comment]
@umarcor Thanks for approving, do you know when this PR might be merged? I'm in the process of forking but would rather point to the official repo

**Comment by umarcor** [comment]
@li0nel, unfortunately, I'm not a maintainer so I can not provide any info apart from the publicly available. Nonetheless, this project is known to prioritise not breaking HEAD consumers before updates/enhancements; I would not wait for this PR to be merged if you are in a rush.

**Comment by sagikazarmark** [comment]
@umarcor If you need features from Viper, you should be able to use 1.8 in your application.

1.8 also clears the dependency tree for Viper. Would be nice to start percolating that through the ecosystem.

**Pull request merged**
