### PR TITLE
Add Meroxa CLI

### PR DESCRIPTION
**Pull request by raulb**
👋,

I'm reaching out in behalf of [Meroxa](https://meroxa.com/) as one of its developers. We've been using [Cobra](https://github.com/spf13/cobra) since our first [initial commit](https://github.com/meroxa/cli/commit/a3301a0199df4c77a9cabf1662f7858110d387e5) back from January 2020, and we recently [launched our Platform](https://techcrunch.com/2021/04/13/meroxa-raises-15m-series-a-for-its-real-time-data-platform/) to the public.

We continue considering using Cobra as our CLI framework and are [actively](https://github.com/meroxa/cli/releases) working on it, and it'd be really nice to be featured as one of the projects using Cobra in the wild.

Thank you!

### CODE REVIEW

**Comment by raulb** [comment]
Looks like the `MINGW64` check will be  be solved by https://github.com/spf13/cobra/pull/1366 so I'll rebase and will re-run CI once it gets merged.

**Review by marckhouzam — APPROVED** [review]
Easy one. /cc @jpmcb

**Comment by raulb** [comment]
@marckhouzam @jpmcb Just updated with latest from master and all checks are passing now. Looks like this should be good to go! Thank you 🙏 .

**Comment by raulb** [comment]
@marckhouzam @jpmcb 👋  wondering if someone else could help out shipping this easy one. Thank you!

**Comment by raulb** [comment]
@marckhouzam @jpmcb This was marked as a stale now even after being approved 😢

**Review by jpmcb — APPROVED** [review]
@raulb Sorry for letting this go stale! Thanks for this!! LGTM :rocket:

**Comment by raulb** [comment]
@jpmcb no worries! Thank you for bringing it home! 🍻

**Pull request merged**
