### PR TITLE
v1.1.0rc

### PR DESCRIPTION
**Pull request by umarcor**
As done in #840, this PR gathers multiple pending PRs, in an effort to help the maintainers get some work out of their tasklist:

<strike>Close #754 (@0robustus1)</strike>
Close #774 (@Brcrwilliams)
Close #841
Close #1044
Close #880 (@swinslow)
Close #896 (@nelz9999)
<strike>Close #929 (@desponda)</strike>
Close #936 (@rhcarvalho)
<strike>Close #937 (@rhcarvalho)</strike>
Close #949
Close #968
Close #1009 (@NickolasHKraus)
<strike>Close #1012</strike>

### CODE REVIEW

**Comment by corneliusweig** [comment]
If my understanding is correct, this PR collects several smaller PRs into a single big one. IMHO it's much more likely that small PRs get merged. So I think this can be closed in favor of the existing small chunks.

**Comment by umarcor** [comment]
@corneliusweig, in the context of the last 15-20 months, #840 proves the opposite. Precisely, those smaller chunks need to be combined and conflicts need to be resolved. Here, all conflicts are resolved already.

**Comment by corneliusweig** [comment]
:thinking: Well #840 combines several trivial patches and touches ~100 lines. This one touches >1k lines and is not as easily reviewable. That's why I suspect that it is unlikely to ever get merged.

But I see that resolving all conflicts has some value to it.

**Comment by umarcor** [comment]
Sinve v1.0.0 was released a few days ago (🎉 🎉 🎉), this PR is now renamed to v1.1.0rc. It is also rebased on top of master.

**Pull request closed without merging**
