### PR TITLE
Add note about hiding a command from completion

### PR DESCRIPTION
**Pull request by eddiezane**

### CODE REVIEW

**Comment by eparis** [comment]
While it is true that setting hidden will hide it from the bash completion list, it also hides it from generated docs, help text, etc. I'd probably rather we update the godoc text https://github.com/spf13/cobra/blob/master/command.go#L74 to describe what all it does rather than scatter it out in the bash completions doc...

**Comment by eddiezane** [comment]
@eparis is there another method to exclude a command from completion? I fumbled around a bit until I found `Hidden`.

**Comment by eparis** [comment]
I can't think of another way....

**Comment by eparis** [comment]
See https://github.com/spf13/cobra/issues/654#issuecomment-381778043 for a mechanism I would accept,

**Comment by eparis** [comment]
Whoops accidental close!

**Pull request closed without merging**
