### PR TITLE
Add the multi-gitter to to projects_using_cobra.md

### PR DESCRIPTION
**Pull request by lindell**

### CODE REVIEW

**Review by marckhouzam — APPROVED** [review]
This technically needs a rebase, but it's safe as is.

**Comment by lindell** [comment]
@marckhouzam Would you prefer a rebase? 🙂

**Comment by marckhouzam** [comment]
This is an easy merge @jpmcb

**Comment by jpmcb** [comment]
Thanks for this! Commit was included in uber PR here: #1454

**Pull request closed without merging**
