### PR TITLE
Include a basic example #465

### PR DESCRIPTION
**Pull request by Jason-Hendry**
#465 Obsolete bash completion example (kubernetes)... and use a better example anyway

### CODE REVIEW

**Comment by eparis** [comment]
This is great. Would you be willing to delete the kubernetes example entirely, and possibly make this an actual go example that shows up in godoc? I also often find that I use `Hidden: true,` in my definition of such a subcommand, so maybe show that, even if it is commented out?

**Comment by itskingori** [comment]
This should be merged. It helped me figure out what the issue was.

**Comment by eparis** [comment]
I'll merge this. But @itskingori any willingness to make a follow so this is an example which shows up in godoc instead of these impenetrable .md files?

**Comment by eparis** [comment]
(and delete the kube example entirely now that we have a much better one?)

**Comment by intel352** [comment]
@eparis what's the `<(bitbucket completion)` bit for?  It occurs twice in the long help command.

**Pull request merged**
