### PR TITLE
Bash Autocompletion Generator

### PR DESCRIPTION
**Pull request by eparis**
That's right.  A golang program the writes a bash program!

### CODE REVIEW

**Comment by eparis** [comment]
Requires https://github.com/spf13/pflag/pull/8 before this will build

**Comment by eparis** [comment]
I pulled out annotations and hard coded a new "ValidArgs" field.  We don't really validate them, but we certainly could...

**Comment by eparis** [comment]
An example of what this can do:

https://github.com/eparis/kubernetes/blob/931044be011e0bd910dcaa7ccbcceb2363195582/contrib/completions/bash/kubectl

**Comment by fabianofranz** [comment]
@eparis Add README docs about how to use it.

**Comment by eparis** [comment]
Now with 55% more README and 32% more tests!

**Comment by fabianofranz** [comment]
Very nice! I could think of a better integration of `ValidArgs` (auto validation of the number of args, receive pointers the same way flags do, etc); but those could be enhancements. Looks good for now.

**Pull request merged**
