### PR TITLE
ci: add workflow_dispatch

### PR DESCRIPTION
**Pull request by umarcor**
The workflow dispatch event allows maintainers or forkers to trigger CI runs either through the web GUI or through the API. See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch.

### CODE REVIEW

**Comment by umarcor** [comment]
*ping* @jpmcb

**Comment by jpmcb** [comment]
> You can manually trigger workflow runs. To trigger specific workflows in a repository, use the workflow_dispatch event.

I'm not sure why we need this? Why would a maintainer need to manually trigger the github actions?

**Comment by umarcor** [comment]
> I'm not sure why we need this? Why would a maintainer need to manually trigger the github actions?

The CI workflow depends on some external dependencies which might change without modifications in the codebase of this repository. Currently, the only solution to have those tested is to rerun an existing workflow, or to push/ammend a "dummy" branch. Having this option avoids that.

Moreover, having this added to the workflow in the default branch will allow users to use the feature in their forks. Hence, even though manually triggering CI might not be used by maintainers of this repo, it can be useful for contributors.

**Comment by umarcor** [comment]
Can we change the milestone of this PR to 1.5.0?

**Comment by marckhouzam** [comment]
> Can we change the milestone of this PR to 1.5.0?

I expect we'll be going through the 2.0.0 and Next milestones and selecting things for 1.5.
I've moved the current PR to 1.5 for now though.

**Comment by umarcor** [comment]
Can we please have this one-liner merged?

**Comment by umarcor** [comment]
*ping* @spf13 @johnSchnake @jpmcb @marckhouzam

**Review by jpmcb — APPROVED** [review]

**Review by marckhouzam — APPROVED** [review]
Sure, why not.

**Pull request merged**
